name = "Mojo"
grammar = "mojo"
path_suffixes = ["mojo", "🔥"]
line_comments = ["# "]
block_comment = ["\"\"\"", "\"\"\""]
tab_size = 4
hard_tabs = false
word_characters = ["_"]
completion_query_characters = [".", "@", ":", "$"]
autoclose_before = ";:.,=}])> \n\t"
collapsible_comments = true

brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false },
    { start = "'", end = "'", close = true, newline = false },
]

